version: '3'

services:
  tenant-registry:
    build:
      context: ./service.tenant.registry
      dockerfile: Dockerfile
    volumes:
      - ./service.tenant.registry:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:8000
